services:
  node:
    image: brunopontiz/bootcamp2.0:0.1
    container_name: node
    ports:
      - 8081:8081
    depends_on:
      - db_bootcamp2

  db_bootcamp2:
    image: mysql:8.4.1
    container_name: db_bootcamp2
    ports:
      - 3306:3306
    env_file: ./app/.env
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: