services:
  node:
    build: .
    container_name: node
    ports:
      - 8081:8081
    depends_on:
      - db_bootcamp2

  db_bootcamp2:
    image: mysql:8.4.1
    container_name: db_bootcamp2
    ports:
      - 3306:3306
    env_file: ./app/.env
    environment:
      - MYSQL_ROOT_PASSWORD=bootsilicecamp101
      - MYSQL_DATABASE=db_bootcamp2
      - MYSQL_USER=nodebootcamp2
      - MYSQL_PASSWORD=bootsilicecamp101
      - MYSQL_HOST=localhost
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: